### ISSUE TITLE
After Update to iOS 13 the App behaves as it is started for the first time

### ISSUE THREAD

**Issue by quotengrote** [tijme/raivo#11]
**Describe the bug**
After Update to iOS 13 the App behaves as it is started for the first time. Including loss of all data.

**To Reproduce**
1. Use RaivoOTP
2. Update OS to iOS 13
3. Open RaivoOTP
4. See Title

**Expected behavior**
The state before the Update should be shown.

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: 13.0

**Comment by tijme** [comment]
Which app version/compilation/build are you using?

Are you using a synchronization provider or offline mode?

**Comment by quotengrote** [comment]
1.1.3 (build-18)
offline
it wasnt enabled

**Comment by tijme** [comment]
Unfortunately I have to tell you that this is indeed a bug, but it was fixed in [Release v.1.1.4](https://github.com/tijme/raivo/releases/tag/build-23).

Did you create a backup of the data via the settings tab?

**Comment by quotengrote** [comment]
Ok, good to know.

No, but it isn't a problem, i've keeping my seed in keepass. ;-)

**Comment by tijme** [comment]
Alright, awesome that you have a backup. I will close the issue for now since this bug has been fixed in Release v1.1.4.

Thanks for the report!
