### ISSUE TITLE
add other logos

### ISSUE THREAD

**Issue by dai640** [tijme/raivo#12]
**Is your feature request related to a problem? Please describe.**
I hope you can add these cloud logo icons, thank you

**Describe the solution you'd like**
[1password's logo](https://1password.com/img/logo-v1-min.png)
[Nutscloud‘s logo](https://www.jianguoyun.com/static/images/logo.png)

**Comment by tijme** [comment]
I've added the 1password logo. Please use the refresh button in the icon search view to refresh the icon cache.

I can't find an SVG logo of Nutscloud, therefore i'm closing the feature request for now. If you find an SVG version of the logo please let me know, so I can add it.
