### ISSUE TITLE
Windows version and syncing

### ISSUE THREAD

**Issue by Kurdym** [tijme/raivo#13]
I use Authy now. Private and business wise.
The two thing I like about Authy is:
- synchronizing
- available on ios and Windows
That way I can copy the 2FA code in the Windows browser, while scanning QR codes with my phone.

I like your tool very much, but have to continue using Authy as long as Raivo cannot sync or is on Windows.

Will you make this possible? 

- kurdy (NL)

**Comment by tijme** [comment]
Hi @Kurdym,

I'm glad that you like Raivo OTP. At the moment I don't have any plans to make a windows application for Raivo, since I don't have enough time to work on it.

When I have some time left again I will reconsider making such an application.
