### ISSUE TITLE
otpauth:// URL support

### ISSUE THREAD

**Issue by midi** [tijme/raivo#14]
For easier import, it would be great if the otpauth:// URL could be supported.

Some other open source iOS 2FA apps do support it:
https://github.com/mattrubin/Authenticator
https://github.com/calleerlandsson/tofu

**Comment by tijme** [comment]
Great idea!

I don't have a lot of time to work on Raivo at the moment, but if I start working on it, this is a feature that will definitely be one of my priorities!

**Comment by tijme** [comment]
This feature will be added in release v1.1.10, which will be pushed to TestFlight today. It might take a few days before Apple approves the TestFlight build.

After some time of beta testing, release v1.1.10 will be pushed to the App Store.
