### ISSUE TITLE
Request 2 logos

### ISSUE THREAD

**Issue by Galiwyx** [tijme/raivo#15]
Hello,

First, thank you very much for your amazing work ! Really, thank you to provide open source apps on iOS ! 

I have a request, can you add in a future update 2 icons ? 

- OVH.com
- Kaspersky 

Thank you :)

**Comment by tijme** [comment]
Would you mind moving this issue to the [icon repository](https://github.com/tijme/raivo-issuer-icons)? Icons can be added by [contributing](https://github.com/tijme/raivo-issuer-icons), or you can just create an issue with the icons you would like to see.
