### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by mil1i** [tijme/raivo#4]
**Is your feature request related to a problem? Please describe.**
Just as the title states, a dark mode! Especially for the OLED iPhones.

**Comment by sdsdsasad12312** [comment]
I think this will be quite easy to implement once Apple releases iOS 13; it comes with a dark mode API for developers. Enabling dark mode in apps is as easy as ticking a box!

**Comment by tijme** [comment]
This sounds like a great idea! The upcoming release will only consist of bug fixes, but I might work on dark mode afterwards. I will keep you updated via this feature request.

**Comment by tijme** [comment]
The upcoming release (1.0.0) is compatible with the iOS 13 dark mode! 😄
