### ISSUE TITLE
Add Option to Edit/Change Icons after adding a new Entry

### ISSUE THREAD

**Issue by quotengrote** [tijme/raivo#6]
**Describe the solution you'd like**
Please add an Option to Edit/Change Icons after the creation of a new entry.

**Comment by tijme** [comment]
You can swipe left on an OTP to update its icon. A "clear current icon" feature will be added in the next release.

**Comment by quotengrote** [comment]
Oh, i didnt noticed this. Sry for opening an issue.

**Comment by tijme** [comment]
Don't worry, I'm happy that you're using Raivo OTP! 👍
