### ISSUE TITLE
Migrating from Authy to Raivo OTP guide improvements

### ISSUE THREAD

**Issue by Bartvdgriendt** [tijme/raivo#7]
I think the [guide ](https://tij.me/blog/migrating-from-authy-to-raivo-otp/#void)on how to migrate from Authy to Raivo OTP could be a little bit more extensive to prevent users to become frustrated because they can't find some little things. :) Some screenshots could be a nice addition.

1. Install Authy from the Chrome Web Store ([link](https://chrome.google.com/webstore/detail/authy/gaedmjdfmmahhbjefcbgaolhhanlaolb?hl=en)).
2. Open the Authy extension and sign in (make sure that the OTPs are visible)
**You could add a explanation that the user need to decrypt the 2FA codes by clicking on one and entering their password. Otherwise the OTP's won't be visible.**
3. Go to the extensions page in Chrome (chrome://extensions/ or Menu > More tools > Extensions)
4. Enable developer mode in the top right corner
5. Find Authy from the list and then click on main.html
**You could add that you need to click on the extension to find the main.html file.**
6. The Chrome developer console should now open.
7. Paste the JavaScript (at the bottom of this page) into your console.
8. You’ll now see QR-codes that you’ll be able to scan using Raivo OTP!
9. When done, close the developer tools, disable developer mode, and uninstall the Authy extension.

I now notice that the guide isn’t mentioned on this Github page or wiki. I think the guide makes it a lot easier to switch to or test Raivo OTP so I would definitely mention it somewhere.

**Comment by tijme** [comment]
Thanks for the input. I agree on all of it and I hope to update the page soon!

**Comment by tijme** [comment]
The guide has been updated in [release 1.2.0](https://github.com/tijme/blog/releases/tag/1.2.0) of the website.
